# Generated by Django 2.2.7 on 2020-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200403_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='jjpt'),
            preserve_default=False,
        ),
    ]
