# Generated by Django 2.2.7 on 2020-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200422_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
