# Generated by Django 2.2.7 on 2020-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_order_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('book', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('Price', models.PositiveIntegerField(default=0)),
                ('totalprice', models.PositiveIntegerField(default=0)),
                ('sum', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='books')),
            ],
        ),
    ]
