# Generated by Django 2.2.7 on 2020-04-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='sum',
        ),
    ]
