# Generated by Django 2.2.7 on 2020-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_history_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.FileField(blank=True, upload_to='books'),
        ),
    ]
