# Generated by Django 2.2.7 on 2020-03-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
