# Generated by Django 2.2.7 on 2020-03-22 12:29

from django.db import migrations, models
import modeels.validation


class Migration(migrations.Migration):

    dependencies = [
        ('modeels', '0002_auto_20200322_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author_email',
            field=models.EmailField(blank=True, max_length=120, null=True, validators=[modeels.validation.validate_author_email]),
        ),
    ]
