# Generated by Django 2.2.7 on 2020-04-03 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('firstname', models.CharField(default='sabin11224231231', max_length=120)),
                ('lastname', models.CharField(default='sabin', max_length=120)),
                ('rollno', models.IntegerField(default=0, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('grade', models.IntegerField(default=0, null=True)),
                ('password', models.CharField(default='sabin', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('uploaded_by', models.CharField(max_length=120)),
                ('dateofpublish', models.DateField()),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('author', models.CharField(max_length=120)),
                ('published_by', models.CharField(max_length=120)),
                ('perprice', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.departments')),
            ],
        ),
        migrations.CreateModel(
            name='orderbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.book')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('totalprice', models.PositiveIntegerField(default=0)),
                ('Prices', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.book')),
                ('books', models.ManyToManyField(to='account.orderbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='Course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.departments'),
        ),
    ]
