# Generated by Django 2.2.7 on 2020-04-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='perprice',
        ),
    ]
