# Generated by Django 2.2.7 on 2020-04-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalprice',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='Price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='totalprice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
